import React, { createContext, useContext, useState, useEffect } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';

export type Language = 'pt' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setCurrentLanguage] = useState<Language>('en');

  useEffect(() => {
    loadLanguage();
  }, []);

  const loadLanguage = async () => {
    try {
      const savedLanguage = await AsyncStorage.getItem('appLanguage');
      if (savedLanguage && (savedLanguage === 'pt' || savedLanguage === 'en')) {
        setCurrentLanguage(savedLanguage as Language);
      } else {
        // Default to English
        setCurrentLanguage('en');
        await AsyncStorage.setItem('appLanguage', 'en');
      }
    } catch (error) {
      console.error('Error loading language:', error);
      // On error, use English as fallback
      setCurrentLanguage('en');
    }
  };

  const setLanguage = async (lang: Language) => {
    try {
      setCurrentLanguage(lang);
      await AsyncStorage.setItem('appLanguage', lang);
    } catch (error) {
      console.error('Error saving language:', error);
    }
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

// Translations object
const translations = {
  pt: {
    // Common
    'save': 'Salvar',
    'cancel': 'Cancelar',
    'edit': 'Editar',
    'delete': 'Excluir',
    'confirm': 'Confirmar',
    'yes': 'Sim',
    'no': 'Não',
    'ok': 'OK',
    'error': 'Erro',
    'success': 'Sucesso',
    'loading': 'Carregando...',
    'saving': 'Salvando...',
    'notInformed': 'Não informado',
    
    // Auth
    'welcomeBack': 'Bem-vindo de volta!',
    'signInToContinue': 'Faça login para continuar',
    'signIn': 'Entrar',
    'signUp': 'Cadastrar',
    'email': 'Email',
    'password': 'Senha',
    'confirmPassword': 'Confirmar Senha',
    'fullName': 'Nome Completo',
    'createAccount': 'Criar Conta',
    'signUpToGetStarted': 'Cadastre-se para começar',
    'dontHaveAccount': 'Não tem uma conta?',
    'alreadyHaveAccount': 'Já tem uma conta?',
    'signingIn': 'Entrando...',
    'creatingAccount': 'Criando conta...',
    'demoCredentials': 'Credenciais de Demonstração',
    'logout': 'Sair',
    'logoutConfirmation': 'Tem certeza que deseja sair?',
    'signOutOfAccount': 'Sair da sua conta',
    'logoutError': 'Falha ao sair. Tente novamente.',
    
    // Password Recovery
    'forgotPassword': 'Esqueceu a Senha?',
    'forgotPasswordDescription': 'Digite seu email para receber instruções de recuperação de senha.',
    'enterYourEmail': 'Digite seu email',
    'sendRecoveryEmail': 'Enviar Email de Recuperação',
    'sending': 'Enviando...',
    'backToLogin': 'Voltar ao Login',
    'emailSent': 'Email Enviado!',
    'recoveryEmailSent': 'Email de Recuperação Enviado',
    'checkEmailInstructions': 'Verifique sua caixa de entrada e siga as instruções para redefinir sua senha.',
    'sentTo': 'Enviado para',
    'nextSteps': 'Próximos Passos',
    'checkInboxSpam': 'Verifique sua caixa de entrada e spam',
    'clickResetLink': 'Clique no link de redefinição no email',
    'createNewPassword': 'Crie uma nova senha segura',
    'resendEmail': 'Reenviar Email',
    'done': 'Concluído',
    'errorOccurred': 'Erro Ocorreu',
    'couldNotSendEmail': 'Não foi possível enviar o email',
    'tryAgain': 'Tentar Novamente',
    'emailNotFound': 'Nenhuma conta encontrada com este email',
    'tooManyRequests': 'Muitas tentativas. Tente novamente mais tarde.',
    'networkError': 'Erro de rede. Verifique sua conexão.',
    'passwordRecoveryError': 'Erro ao enviar email de recuperação',
    
    // Validation
    'emailRequired': 'Email é obrigatório',
    'emailInvalid': 'Email inválido',
    'passwordRequired': 'Senha é obrigatória',
    'passwordMinLength': 'Senha deve ter pelo menos 6 caracteres',
    'nameRequired': 'Nome é obrigatório',
    'nameMinLength': 'Nome deve ter pelo menos 2 caracteres',
    'confirmPasswordRequired': 'Confirmação de senha é obrigatória',
    'passwordsDoNotMatch': 'Senhas não coincidem',
    'emailAlreadyExists': 'Este email já está cadastrado',
    'passwordTooWeak': 'Senha muito fraca',
    
    // Navigation
    'home': 'Início',
    'progress': 'Progresso',
    'profile': 'Perfil',
    'settings': 'Configurações',
    'menu': 'Menu',
    
    // Home Screen
    'hello': 'Olá',
    'howIsYourProgress': 'Como está seu progresso hoje?',
    'dailyCheckIn': 'Check-in Diário',
    'completedToday': '✅ Concluído hoje!',
    'markAsCompleted': '⏰ Marcar como concluído',
    'alreadyCompletedToday': '🔒 Já concluído hoje',
    'dailyCheckCompleted': 'Check-in Diário Concluído',
    'nextCheckInAvailable': 'Você já fez seu check-in hoje! O próximo check-in estará disponível à meia-noite.',
    'nextCheckInTomorrow': 'Próximo check-in disponível amanhã à meia-noite',
    'tapToRegister': 'Toque para registrar seu uso diário',
    'monthlyProgress': 'Progresso Mensal',
    'excellentConsistency': '🎉 Excelente consistência!',
    'goodProgress': '👍 Bom progresso, continue!',
    'letsImprove': '⚡ Vamos melhorar juntos!',
    'focusOnConsistency': '💪 Foco na consistência!',
    'totalDays': 'Total de Dias',
    'completedDays': 'dias concluídos',
    'currentStreak': 'Sequência Atual',
    'consecutive': 'consecutivos',
    'dailyAverage': 'Média Diária',
    'perDay': 'por dia',
    'consistency': 'Consistência',
    'last30Days': 'últimos 30 dias',
    'quickActions': 'Ações Rápidas',
    'setupReminder': 'Configurar Lembrete',
    'monthlyProgress': 'Progresso Mensal',
    'currentMonth': 'Atual',
    'monthlyGoal': 'Meta Mensal',
    'current': 'Atual',
    'dailyRecommendedDosage': '💊 Dosagem Diária Recomendada',
    'important2Capsules': '⚠️ IMPORTANTE: 2 Cápsulas Diárias',
    'dosageDescription': 'Para obter os melhores resultados com o MaxTestorin, é essencial manter a dosagem de 2 cápsulas por dia.',
    'capsulesPerDay': '2 cápsulas por dia',
    'takeSameTime': '• Tome sempre no mesmo horário',
    'preferablyMorning': '• Preferencialmente pela manhã',
    'canBeDiluted': '• Pode ser diluído em água',
    'maintainRegularity': '• Mantenha a regularidade diária',
    'aboutMaxTestorin': 'Sobre o MaxTestorin',
    'productDescription': 'O MaxTestorin é um suplemento nutracêutico em gotas desenvolvido para apoiar o bem-estar masculino. Cada gota contém ingredientes naturais cuidadosamente selecionados para máxima eficácia.',
    
    // Register Screen
    'registerUse': 'Registrar Uso',
    'registerDailyUse': 'Registre seu uso diário do MaxTestorin',
    'dropsQuantity': 'Quantidade de Gotas',
    'enterDropsNumber': 'Digite o número de gotas',
    'capsulesQuantity': 'Quantidade de Cápsulas',
    'enterCapsulesNumber': 'Digite o número de cápsulas',
    'time': 'Horário',
    'observations': 'Observações (opcional)',
    'addObservations': 'Adicione observações sobre o uso...',
    'saveRecord': 'Salvar Registro',
    'saving': 'Salvando...',
    'quickAccess': 'Acesso rápido (Recomendado: 40 gotas):',
    'quickAccessCapsules': 'Acesso rápido (Recomendado: 2 cápsulas):',
    'usageTips': 'Dicas de Uso',
    'tip1': '• Use o MaxTestorin preferencialmente pela manhã',
    'tip2': '• Mantenha regularidade nos horários',
    'tip3': '• Registre imediatamente após o uso',
    'tip4': '• Observe os efeitos e anote observações',
    'recordSaved': 'Registro Salvo!',
    'incorrectDosage': '⚠️ Dosagem Incorreta',
    'dosageWarning': 'A dosagem recomendada é de 2 cápsulas diárias.\n\nVocê inseriu: {capsules} cápsulas\nRecomendado: 2 cápsulas\n\nDeseja continuar mesmo assim?',
    'correct': 'Corrigir',
    'continue': 'Continuar',
    'congratulations': '🎉 Parabéns!',
    'recordSavedSuccess': 'Registro salvo com sucesso!',
    'todayRecordUpdated': '✅ Sucesso',
    'recordUpdatedSuccess': 'Registro de hoje atualizado com sucesso!',
    
    // Progress Screen
    'progress': 'Progresso',
    'trackYourDevelopment': 'Acompanhe seu desenvolvimento',
    'days': 'dias',
    'dailyDropsUsage': 'Uso Diário de Gotas',
    'dailyCapsulesUsage': 'Uso Diário de Cápsulas',
    'completed2Capsules': 'Concluído (2 cápsulas)',
    'notRegistered': 'Não registrado',
    'periodStatistics': 'Estatísticas do Período',
    'monthlyStatistics': 'Estatísticas Mensais',
    'ofDays': 'de {total} dias',
    'inPeriod': 'no período',
    'inMonth': 'no mês',
    'dropsPerDay': 'gotas/dia',
    'capsulesPerDay': 'cápsulas/dia',
    'completionRate': 'taxa de conclusão',
    'recentRecords': 'Registros Recentes',
    'clearRecords': 'Limpar Registros',
    'clearAllRecords': '🗑️ Limpar Todos os Registros',
    'clearWarning': 'ATENÇÃO: Esta ação irá remover PERMANENTEMENTE:\n\n• Todos os registros diários\n• Histórico de progresso\n• Estatísticas acumuladas\n• Dados do gráfico\n\n⚠️ Esta ação NÃO PODE ser desfeita!',
    'yesDeleteAll': 'SIM, LIMPAR TUDO',
    'cleaningCompleted': '✅ Limpeza Concluída',
    'allRecordsRemoved': 'Todos os registros foram removidos permanentemente.\n\nVocê pode começar um novo acompanhamento agora!',
    'couldNotClearRecords': '❌ Erro',
    'noRecordsFound': 'Nenhum registro encontrado',
    'consistencyGoal': 'Meta de Consistência: 80%',
    'goal': 'Meta: 80%',
    'maintainConsistency': 'Mantenha a consistência para melhores resultados',
    
    // Profile Screen
    'profile': 'Perfil',
    'managePersonalInfo': 'Gerencie suas informações pessoais',
    'ageNotInformed': 'Idade não informada',
    'nameNotInformed': 'Nome não informado',
    'managePersonalData': 'Gerenciar Dados Pessoais',
    'editModeActive': 'Modo de edição ativo - Altere os campos abaixo',
    'viewOrEditInfo': 'Visualize ou edite suas informações pessoais',
    'cancelEdit': 'Cancelar Edição',
    'editInformation': 'Editar Informações',
    'fullName': 'Nome Completo *',
    'dateOfBirth': 'Data de Nascimento *',
    'profileGender': 'Perfil',
    'male': 'Masculino',
    'other': 'Outro',
    'contactEmail': 'Email de Contato',
    'contactPhone': 'Telefone de Contato',
    'treatmentStartDate': 'Data de Início do Tratamento *',
    'firstLoginDate': 'Data do Primeiro Login',
    'treatmentStartedOn': 'Tratamento iniciado em',
    'saveChanges': 'Salvar Alterações',
    'confirmChanges': 'Confirme as alterações realizadas nos seus dados pessoais',
    'discard': 'Descartar',
    'saveData': 'Salvar Dados',
    'statistics': 'Estatísticas',
    'usingMaxTestorin': 'Usando MaxTestorin',
    'profilePhoto': 'Foto de Perfil',
    'choosePhotoOption': 'Escolha uma opção para adicionar sua foto:',
    'gallery': 'Galeria',
    'camera': 'Câmera',
    'permissionNeeded': 'Permissão Necessária',
    'galleryPermission': 'É necessário permitir acesso à galeria para selecionar uma foto.',
    'cameraPermission': 'É necessário permitir acesso à câmera para tirar uma foto.',
    'couldNotSelectImage': 'Não foi possível selecionar a imagem.',
    'couldNotTakePhoto': 'Não foi possível tirar a foto.',
    'uploading': 'Enviando...',
    'uploadingImage': 'Enviando imagem para o servidor...',
    'imageUploadedSuccess': 'Imagem enviada com sucesso!',
    'couldNotUploadImage': 'Não foi possível enviar a imagem.',
    'profileUpdatedSuccess': 'Perfil atualizado com sucesso!',
    'couldNotSaveProfile': 'Não foi possível salvar o perfil.',
    'years': 'anos',
    
    // Settings Screen
    'settings': 'Configurações',
    'customizeExperience': 'Personalize sua experiência',
    'appearance': 'Aparência',
    'theme': 'Tema',
    'darkModeEnabled': 'Modo escuro ativado',
    'lightModeEnabled': 'Modo claro ativado',
    'help': 'Ajuda',
    'notifications': 'Notificações',
    'dailyReminders': 'Lembretes Diários',
    'receiveNotifications': 'Receba notificações para registrar o uso',
    'goals': 'Metas',
    'dailyGoal': 'Meta Diária',
    'mandatoryDosage': '2 cápsulas por dia (Dosagem Obrigatória)',
    'weeklyGoal': 'Meta Semanal',
    'weeklyDosage': '14 cápsulas por semana (7 x 2 cápsulas)',
    'data': 'Dados',
    'exportData': 'Exportar Dados',
    'backupRecords': 'Fazer backup dos seus registros',
    'clearData': 'Limpar Dados',
    'deleteAllRecords': 'Apagar todos os registros',
    'information': 'Informações',
    'aboutMaxTestorin': 'Sobre o MaxTestorin',
    'productInformation': 'Informações sobre o produto',
    'privacy': 'Privacidade',
    'privacyPolicy': 'Política de privacidade',
    'shareApp': 'Compartilhar App',
    'inviteFriends': 'Convidar amigos',
    'language': 'Idioma',
    'account': 'Conta',
    'signOutOfAccount': 'Sair da sua conta',
    'personalInformation': 'Informações Pessoais',
    'selectLanguage': 'Selecionar idioma',
    'portuguese': 'Português',
    'english': 'English',
    'language': 'Idioma',
    'lightMode': 'Modo Claro',
    'darkMode': 'Modo Escuro',
    'helpAndSupport': 'Ajuda e Suporte',
    'shareApplication': 'Compartilhar App',
    'developmentFeature': 'Funcionalidade em desenvolvimento',
    'reminderConfigured': 'Lembrete Configurado',
    'dailyNotification': 'Você será notificado diariamente para registrar o uso do MaxTestorin.',
    'exportDataFeature': 'Esta funcionalidade permite exportar seus dados para backup.',
    'inviteFriendsFeature': 'Convide amigos para usar o MaxTestorin Tracker!',
    'correctDosageInfo': '💊 Dosagem Correta do MaxTestorin',
    'dosageInfo': 'IMPORTANTE: A dosagem recomendada é de 2 cápsulas diárias.\n\nIngredientes principais:\n• Extrato de Tribulus Terrestris\n• Maca Peruana\n• Zinco\n• Vitamina D3\n• Magnésio\n\nModo de uso:\n• 2 cápsulas por dia (OBRIGATÓRIO)\n• Preferencialmente pela manhã\n• Pode ser tomado com água\n• Manter regularidade diária',
    'privacyPolicyInfo': 'Seus dados são armazenados localmente no seu dispositivo e não são compartilhados com terceiros. Levamos sua privacidade a sério.',
    'appVersion': 'MaxTestorin Tracker v1.0.0',
    'developedFor': 'Desenvolvido para acompanhar seu progresso',
    
    // Logout/Exit
    'exitApp': 'Sair do Aplicativo',
    'exitAppConfirmation': 'Tem certeza que deseja sair do aplicativo?',
    
    // Clear Data Functionality
    'clearData': 'Limpar Dados',
    'clearDataWarning': 'ATENÇÃO: Esta ação irá remover PERMANENTEMENTE todos os dados do aplicativo:\n\n• Registros diários de uso\n• Informações do perfil\n• Configurações personalizadas\n• Histórico de progresso\n• Todas as estatísticas\n\n⚠️ Esta ação NÃO PODE ser desfeita!\n\nTem certeza que deseja continuar?',
    'allDataRemoved': 'Todos os dados foram removidos com sucesso.',
    'couldNotRemoveData': 'Não foi possível remover os dados. Tente novamente.',
    
    // MaxTestorin Info Popup
    'aboutMaxTestorinTitle': 'Sobre o MaxTestorin',
    'aboutMaxTestorinDescription': 'O MaxTestorin é um suplemento nutracêutico em gotas desenvolvido para apoiar o bem-estar masculino. Cada gota contém ingredientes naturais cuidadosamente selecionados para máxima eficácia.',
    'privacyPolicyTitle': 'Política de Privacidade',
    'privacyPolicyDescription': 'Sua privacidade é nossa prioridade. Este aplicativo foi desenvolvido com foco na proteção dos seus dados pessoais:\n\n• Todos os dados são armazenados LOCALMENTE no seu dispositivo\n• Nenhuma informação é enviada para servidores externos\n• Não coletamos dados pessoais ou de uso\n• Não compartilhamos informações com terceiros\n• Você tem controle total sobre seus dados\n• Pode exportar ou excluir seus dados a qualquer momento\n\nSeus registros de uso do MaxTestorin permanecem privados e seguros em seu dispositivo.',
    'close': 'Fechar',
    
    // Help and Support
    'helpAndSupport': 'Ajuda e Suporte',
    'needHelp': 'Precisa de Ajuda?',
    'helpDescription': 'Nossa equipe de suporte está pronta para ajudá-lo com qualquer dúvida sobre o MaxTestorin ou o aplicativo.',
    'emailSupport': 'Suporte por Email',
    'emailSupportDescription': 'Envie suas dúvidas e receba resposta em até 24 horas',
    'contactSupport': 'Entrar em Contato',
    'copyEmailManually': 'Copie o email manualmente para entrar em contato',
    'copyEmail': 'Copiar Email',
    'emailCopied': 'Email copiado',
    'copyLink': 'Copiar Link',
    'frequentQuestions': 'Perguntas Frequentes',
    'faq1': 'Como usar o MaxTestorin corretamente?',
    'faq2': 'Qual a dosagem recomendada diária?',
    'faq3': 'Como acompanhar meu progresso?',
    'faq4': 'Como fazer backup dos meus dados?',
    
    // Share App Modal
    'shareAppTitle': 'Compartilhar Aplicativo',
    'shareAppDescription': '🚀 Ajude seus amigos a maximizar seus resultados!\n\n💪 O MaxTestorin Tracker é o aplicativo perfeito para homens que querem:\n\n✅ Acompanhar o uso do MaxTestorin diariamente\n✅ Monitorar progresso e consistência\n✅ Manter disciplina no tratamento\n✅ Alcançar melhores resultados\n\n🎯 Compartilhe com seus amigos homens e ajude-os a ter o mesmo sucesso que você!\n\n📱 Link do aplicativo:\napp.maxtestorin.com',
    
    // Validation Messages
    'enterValidDrops': 'Por favor, insira uma quantidade válida de gotas.',
    'enterValidCapsules': 'Por favor, insira uma quantidade válida de cápsulas.',
    'enterTime': 'Por favor, insira o horário do uso.',
    'couldNotSaveRecord': 'Não foi possível salvar o registro.',
    'couldNotUpdateCompletion': 'Não foi possível atualizar o registro.',
    'couldNotRemoveData': 'Não foi possível remover os dados.',
    'allDataRemoved': 'Todos os dados foram removidos.',
    
    // Profile specific translations
    'cityAndState': 'Cidade e Estado',
    'treatmentGoal': 'Objetivo do Tratamento',
    
    // Shop Screen
    'shop': 'Loja',
    'premiumNutraceuticalProducts': 'Produtos Nutracêuticos Premium',
    'maxTestorin6BottlePackage': 'MAX TESTORIN\nPACOTE 6 FRASCOS',
    'maxTestorin3BottlePackage': 'MAX TESTORIN\nPACOTE 3 FRASCOS',
    'maxTestorin1BottlePackage': 'MAX TESTORIN\nPACOTE 1 FRASCO',
    'bestValue': 'MELHOR VALOR',
    'youAreSaving': 'VOCÊ ESTÁ ECONOMIZANDO $',
    'onlyPerBottle': 'apenas $',
    'perBottle': 'por frasco',
    'total': 'total',
    'claimOfferNow': 'GARANTIR OFERTA AGORA',
    'buyNow': 'COMPRAR AGORA',
    'save': 'ECONOMIZE $',
    'confirmPurchase': 'Confirmar Compra',
    'aboutToPurchase': 'Você está prestes a comprar:',
    'price': 'Preço',
    'savings': 'Economia',
    'wantToContinue': 'Deseja continuar?',
    'purchaseSuccess': 'Sucesso!',
    'redirectingToPayment': 'Redirecionando para o pagamento...',
    'otherAvailablePackages': 'Outros Pacotes Disponíveis',
    'aboutMaxTestorin': 'Sobre o MAX TESTORIN',
    'premiumNutraceuticalFormula': 'Fórmula nutracêutica premium desenvolvida para máxima performance e resultados. Cada frasco contém ingredientes naturais cuidadosamente selecionados para eficácia ideal.',
    'premiumNutraceuticalFormulaShort': 'Premium formula with selected natural ingredients for maximum efficacy and results.',
    'enhancedEnergyVitality': 'Energia e vitalidade aprimoradas',
    'naturalIngredientFormula': 'Fórmula de ingredientes naturais',
    'moneyBackGuarantee': 'Garantia de 180 dias',
    'freeWorldwideShipping': 'Frete grátis mundial',
    'dayGuarantee': '180 Dias',
    'freeShip': 'Frete Grátis',
    'secure': 'Seguro',
    'featuresGuarantees': 'Recursos e Garantias',
    'paymentMethods': 'Métodos de Pagamento',
    'premiumFormula': 'Fórmula Premium',
    'naturalIngredients': 'Ingredientes Naturais',
    'moneyBackGuaranteeTitle': 'Garantia de Devolução',
    'freeWorldwideShippingTitle': 'Frete Grátis Mundial',
    'qualityAssured': 'Qualidade Garantida',
    'testedCertified': 'Testado e certificado para máxima eficácia',
    'continueTheTreatment': 'Continue o tratamento, adicione mais unidades.',
    'premiumFormulaDescription': 'Fórmula premium com ingredientes naturais selecionados para máxima eficácia e resultados.',
    'totalDrops': 'Total de Gotas',
    'totalCapsules': 'Total de Cápsulas',
    'swipeToSeeMore': 'Deslize para ver mais pacotes',
    'averageDrops': 'Média Diária',
    'averageCapsules': 'Média Diária',
    'remaining': 'Restantes',
    'drops': 'gotas',
    'capsules': 'cápsulas',
    'capsule': 'cápsula',
    'at': 'às',
    'records': 'registros',
    'monthlyRecords': 'Registros Mensais',
    'monthlyDaysStatus': 'Status dos Dias do Mês',
    'daysCompleted': 'dias completados',
    'completed': 'Completado',
    
    // Month names
    'january': 'Janeiro',
    'february': 'Fevereiro',
    'march': 'Março',
    'april': 'Abril',
    'may': 'Maio',
    'june': 'Junho',
    'july': 'Julho',
    'august': 'Agosto',
    'september': 'Setembro',
    'october': 'Outubro',
    'november': 'Novembro',
    'december': 'Dezembro',
    
    // Purchase notifications
    'purchased': 'comprou',
    
    // Tutorial
    'tutorialTitle': 'Maximize Seus Resultados com o MaxTestorin Tracker!',
    'tutorialSubtitle': 'Assista este tutorial rápido para aproveitar ao máximo seu aplicativo',
    'skipTutorial': 'Pular Tutorial',
    'watchLater': 'Assistir Depois',
    'welcomeTutorial': 'Tutorial de Boas-Vindas',
    'loadingVideo': 'Carregando vídeo...',
    
    // Guides Screen
    'guides': 'Guias',
    'learningMaterials': 'Materiais de aprendizado e recursos',
    'categories': 'Categorias',
    'allCategories': 'Todas',
    'nutrition': 'Nutrição',
    'exercise': 'Exercícios',
    'lifestyle': 'Estilo de Vida',
    'science': 'Ciência',
    'featuredGuides': 'Guias em Destaque',
    'allGuides': 'Todos os Guias',
    'items': 'itens',
    'downloadPDF': 'Baixar PDF',
    'watchVideo': 'Assistir Vídeo',
    'readArticle': 'Ler Artigo',
    'downloadStarted': 'Download Iniciado',
    'downloadStartedMessage': 'O download de "{title}" foi iniciado.',
    'cannotOpenFile': 'Não foi possível abrir o arquivo.',
    'cannotOpenVideo': 'Não foi possível abrir o vídeo.',
    'articleContentNotAvailable': 'Conteúdo do artigo não disponível.',
    'errorOpeningGuide': 'Erro ao abrir o guia.',
    'noGuidesFound': 'Nenhum guia encontrado',
    'tryDifferentCategory': 'Tente uma categoria diferente ou pesquise por outro termo.',
    'aboutGuides': 'Sobre os Guias',
    'guidesDescription': 'Nossa biblioteca de guias oferece informações científicas, dicas práticas e recursos educacionais para maximizar seus resultados com o MaxTestorin. Todos os materiais são desenvolvidos por especialistas.',
    
    // Guide Content
    'maxTestorinCompleteGuide': 'Guia Completo do MaxTestorin',
    'completeGuideDescription': 'Manual completo com tudo que você precisa saber sobre o MaxTestorin: composição, benefícios, modo de uso e resultados esperados.',
    'nutritionOptimizationGuide': 'Guia de Otimização Nutricional',
    'nutritionGuideDescription': 'Estratégias nutricionais para potencializar os efeitos do MaxTestorin e melhorar sua saúde geral.',
    'exerciseRoutineVideo': 'Rotina de Exercícios Complementares',
    'exerciseVideoDescription': 'Vídeo com exercícios específicos que complementam o uso do MaxTestorin para melhores resultados.',
    'lifestyleTipsArticle': 'Dicas de Estilo de Vida',
    'lifestyleTipsDescription': 'Artigo com dicas práticas de estilo de vida para maximizar os benefícios do tratamento.',
    'scientificStudyPDF': 'Estudos Científicos',
    'scientificStudyDescription': 'Compilação de estudos científicos sobre os ingredientes e eficácia do MaxTestorin.',
    'supplementationGuide': 'Guia de Suplementação',
    'supplementationDescription': 'Manual detalhado sobre como combinar o MaxTestorin com outros suplementos de forma segura.',
    
    // Guide Detail Modal
    'downloads': 'Downloads',
    'rating': 'Avaliação',
    'size': 'Tamanho',
    'duration': 'Duração',
    'rateThisGuide': 'Avalie este Guia',
    'thankYou': 'Obrigado!',
    'ratingSubmitted': 'Sua avaliação foi enviada com sucesso.',
    'errorSubmittingRating': 'Erro ao enviar avaliação.',
    'downloading': 'Baixando...',
    'opening': 'Abrindo...',
    'viewDetails': 'Ver Detalhes',
  },
  en: {
    // Common
    'save': 'Save',
    'cancel': 'Cancel',
    'edit': 'Edit',
    'delete': 'Delete',
    'confirm': 'Confirm',
    'yes': 'Yes',
    'no': 'No',
    'ok': 'OK',
    'error': 'Error',
    'success': 'Success',
    'loading': 'Loading...',
    'saving': 'Saving...',
    'notInformed': 'Not informed',
    
    // Auth
    'welcomeBack': 'Welcome Back!',
    'signInToContinue': 'Sign in to continue',
    'signIn': 'Sign In',
    'signUp': 'Sign Up',
    'email': 'Email',
    'password': 'Password',
    'confirmPassword': 'Confirm Password',
    'fullName': 'Full Name',
    'createAccount': 'Create Account',
    'signUpToGetStarted': 'Sign up to get started',
    'dontHaveAccount': "Don't have an account?",
    'alreadyHaveAccount': 'Already have an account?',
    'signingIn': 'Signing in...',
    'creatingAccount': 'Creating account...',
    'demoCredentials': 'Demo Credentials',
    'forgotPassword': 'Forgot Password',
    'forgotPasswordMessage': 'Enter your email to receive password recovery instructions.',
    'sendInstructions': 'Send Instructions',
    'emailSent': 'Email Sent!',
    'checkEmailInstructions': 'Check your inbox and follow the instructions to reset your password.',
    'logout': 'Logout',
    'logoutConfirmation': 'Are you sure you want to logout?',
    'signOutOfAccount': 'Sign out of your account',
    'logoutError': 'Failed to logout. Please try again.',
    
    // Password Recovery
    'forgotPassword': 'Forgot Password?',
    'forgotPasswordDescription': 'Enter your email to receive password recovery instructions.',
    'enterYourEmail': 'Enter your email',
    'sendRecoveryEmail': 'Send Recovery Email',
    'sending': 'Sending...',
    'backToLogin': 'Back to Login',
    'emailSent': 'Email Sent!',
    'recoveryEmailSent': 'Recovery Email Sent',
    'checkEmailInstructions': 'Check your inbox and follow the instructions to reset your password.',
    'sentTo': 'Sent to',
    'nextSteps': 'Next Steps',
    'checkInboxSpam': 'Check your inbox and spam folder',
    'clickResetLink': 'Click the reset link in the email',
    'createNewPassword': 'Create a new secure password',
    'resendEmail': 'Resend Email',
    'done': 'Done',
    'errorOccurred': 'Error Occurred',
    'couldNotSendEmail': 'Could not send email',
    'tryAgain': 'Try Again',
    'emailNotFound': 'No account found with this email address',
    'tooManyRequests': 'Too many attempts. Please try again later.',
    'networkError': 'Network error. Please check your connection.',
    'passwordRecoveryError': 'Error sending recovery email',
    
    // Validation
    'emailRequired': 'Email is required',
    'emailInvalid': 'Invalid email',
    'passwordRequired': 'Password is required',
    'passwordMinLength': 'Password must be at least 6 characters',
    'nameRequired': 'Name is required',
    'nameMinLength': 'Name must be at least 2 characters',
    'confirmPasswordRequired': 'Password confirmation is required',
    'passwordsDoNotMatch': 'Passwords do not match',
    'emailAlreadyExists': 'This email is already registered',
    'passwordTooWeak': 'Password is too weak',
    
    // Shop Screen
    'shop': 'Shop',
    'premiumNutraceuticalProducts': 'Premium Nutraceutical Products',
    'maxTestorin6BottlePackage': 'MAX TESTORIN\n6 BOTTLE PACKAGE',
    'maxTestorin3BottlePackage': 'MAX TESTORIN\n3 BOTTLE PACKAGE',
    'maxTestorin1BottlePackage': 'MAX TESTORIN\n1 BOTTLE PACKAGE',
    'bestValue': 'BEST VALUE',
    'youAreSaving': 'YOU\'RE SAVING $',
    'onlyPerBottle': 'only $',
    'perBottle': 'per bottle',
    'total': 'total',
    'claimOfferNow': 'CLAIM OFFER NOW',
    'buyNow': 'BUY NOW',
    'save': 'SAVE $',
    'confirmPurchase': 'Confirm Purchase',
    'aboutToPurchase': 'You are about to purchase:',
    'price': 'Price',
    'savings': 'Savings',
    'wantToContinue': 'Do you want to continue?',
    'purchaseSuccess': 'Success!',
    'redirectingToPayment': 'Redirecting to payment...',
    'otherAvailablePackages': 'Other Available Packages',
    'aboutMaxTestorin': 'About MAX TESTORIN',
    'premiumNutraceuticalFormula': 'Premium nutraceutical formula designed for maximum performance and results. Each bottle contains carefully selected natural ingredients for optimal effectiveness.',
    'premiumNutraceuticalFormulaShort': 'Fórmula premium com ingredientes naturais selecionados para máxima eficácia e resultados.',
    'enhancedEnergyVitality': 'Enhanced energy and vitality',
    'naturalIngredientFormula': 'Natural ingredient formula',
    'moneyBackGuarantee': '180-day money-back guarantee',
    'freeWorldwideShipping': 'Free worldwide shipping',
    'dayGuarantee': '180-Day',
    'freeShip': 'Free Ship',
    'secure': 'Secure',
    'featuresGuarantees': 'Features & Guarantees',
    'paymentMethods': 'Payment Methods',
    'premiumFormula': 'Premium Formula',
    'naturalIngredients': 'Natural Ingredients',
    'moneyBackGuaranteeTitle': 'Money Back Guarantee',
    'freeWorldwideShippingTitle': 'Free Worldwide Shipping',
    'qualityAssured': 'Quality Assured',
    'testedCertified': 'Tested and certified for maximum effectiveness',
    'continueTheTreatment': 'Continue the treatment, add more units.',
    'premiumFormulaDescription': 'Premium formula with selected natural ingredients for maximum efficacy and results.',
    
    // Navigation
    'home': 'Home',
    'progress': 'Progress',
    'profile': 'Profile',
    'settings': 'Settings',
    'menu': 'Menu',
    
    // Home Screen
    'hello': 'Hello',
    'howIsYourProgress': 'How is your progress today?',
    'dailyCheckIn': 'Daily Check-in',
    'completedToday': '✅ Completed today!',
    'markAsCompleted': '⏰ Mark as completed',
    'alreadyCompletedToday': '🔒 Already completed today',
    'dailyCheckCompleted': 'Daily Check-in Completed',
    'nextCheckInAvailable': 'You have already completed your check-in today! Next check-in will be available at midnight.',
    'nextCheckInTomorrow': 'Next check-in available tomorrow at midnight',
    'tapToRegister': 'Tap to register your daily use',
    'monthlyProgress': 'Monthly Progress',
    'excellentConsistency': '🎉 Excellent consistency!',
    'goodProgress': '👍 Good progress, keep going!',
    'letsImprove': '⚡ Let\'s improve together!',
    'focusOnConsistency': '💪 Focus on consistency!',
    'totalDays': 'Total Days',
    'completedDays': 'completed days',
    'currentStreak': 'Current Streak',
    'consecutive': 'consecutive',
    'dailyAverage': 'Daily Average',
    'perDay': 'per day',
    'consistency': 'Consistency',
    'last30Days': 'last 30 days',
    'quickActions': 'Quick Actions',
    'setupReminder': 'Setup Reminder',
    'monthlyProgress': 'Monthly Progress',
    'currentMonth': 'Current',
    'monthlyGoal': 'Monthly Goal',
    'current': 'Current',
    'dailyRecommendedDosage': '💊 Daily Recommended Dosage',
    'important2Capsules': '⚠️ IMPORTANT: 2 Daily Capsules',
    'dosageDescription': 'To get the best results with MaxTestorin, it is essential to maintain the dosage of',
    'capsulesPerDay': '2 capsules per day',
    'takeSameTime': '• Always take at the same time',
    'preferablyMorning': '• Preferably in the morning',
    'canBeDiluted': '• Can be diluted in water',
    'maintainRegularity': '• Maintain daily regularity',
    'aboutMaxTestorin': 'About MaxTestorin',
    'productDescription': 'MaxTestorin is a nutraceutical supplement in drops developed to support male well-being. Each drop contains natural ingredients carefully selected for maximum efficacy.',
    
    // Register Screen
    'registerUse': 'Register Use',
    'registerDailyUse': 'Register your daily MaxTestorin use',
    'dropsQuantity': 'Drops Quantity',
    'enterDropsNumber': 'Enter the number of drops',
    'capsulesQuantity': 'Capsules Quantity',
    'enterCapsulesNumber': 'Enter the number of capsules',
    'time': 'Time',
    'observations': 'Observations (optional)',
    'addObservations': 'Add observations about the use...',
    'saveRecord': 'Save Record',
    'saving': 'Saving...',
    'quickAccess': 'Quick access (Recommended: 40 drops):',
    'quickAccessCapsules': 'Quick access (Recommended: 2 capsules):',
    'usageTips': 'Usage Tips',
    'tip1': '• Use MaxTestorin preferably in the morning',
    'tip2': '• Maintain regularity in schedules',
    'tip3': '• Register immediately after use',
    'tip4': '• Observe effects and note observations',
    'recordSaved': 'Record Saved!',
    'incorrectDosage': '⚠️ Incorrect Dosage',
    'dosageWarning': 'The recommended dosage is 2 capsules daily.\n\nYou entered: {capsules} capsules\nRecommended: 2 capsules\n\nDo you want to continue anyway?',
    'correct': 'Correct',
    'continue': 'Continue',
    'congratulations': '🎉 Congratulations!',
    'recordSavedSuccess': 'Record saved successfully!',
    'todayRecordUpdated': '✅ Success',
    'recordUpdatedSuccess': 'Today\'s record updated successfully!',
    
    // Progress Screen
    'progress': 'Progress',
    'trackYourDevelopment': 'Track your development',
    'days': 'days',
    'dailyDropsUsage': 'Daily Drops Usage',
    'dailyCapsulesUsage': 'Daily Capsules Usage',
    'completed2Capsules': 'Completed (2 capsules)',
    'notRegistered': 'Not registered',
    'periodStatistics': 'Period Statistics',
    'monthlyStatistics': 'Monthly Statistics',
    'ofDays': 'of {total} days',
    'inPeriod': 'in period',
    'inMonth': 'in month',
    'dropsPerDay': 'drops/day',
    'capsulesPerDay': 'capsules/day',
    'completionRate': 'completion rate',
    'recentRecords': 'Recent Records',
    'clearRecords': 'Clear Records',
    'clearAllRecords': '🗑️ Clear All Records',
    'clearWarning': 'WARNING: This action will PERMANENTLY remove:\n\n• All daily records\n• Progress history\n• Accumulated statistics\n• Chart data\n\n⚠️ This action CANNOT be undone!',
    'yesDeleteAll': 'YES, CLEAR ALL',
    'cleaningCompleted': '✅ Cleaning Completed',
    'allRecordsRemoved': 'All records have been permanently removed.\n\nYou can start a new tracking now!',
    'couldNotClearRecords': '❌ Error',
    'noRecordsFound': 'No records found',
    'consistencyGoal': 'Consistency Goal: 80%',
    'goal': 'Goal: 80%',
    'maintainConsistency': 'Maintain consistency for better results',
    
    // Profile Screen
    'profile': 'Profile',
    'managePersonalInfo': 'Manage your personal information',
    'ageNotInformed': 'Age not informed',
    'nameNotInformed': 'Name not informed',
    'managePersonalData': 'Manage Personal Data',
    'editModeActive': 'Edit mode active - Change the fields below',
    'viewOrEditInfo': 'View or edit your personal information',
    'cancelEdit': 'Cancel Edit',
    'editInformation': 'Edit Information',
    'fullName': 'Full Name *',
    'dateOfBirth': 'Date of Birth *',
    'profileGender': 'Profile',
    'male': 'Male',
    'other': 'Other',
    'contactEmail': 'Contact Email',
    'contactPhone': 'Contact Phone',
    'treatmentStartDate': 'Treatment Start Date *',
    'firstLoginDate': 'First Login Date',
    'treatmentStartedOn': 'Treatment started on',
    'saveChanges': 'Save Changes',
    'confirmChanges': 'Confirm the changes made to your personal data',
    'discard': 'Discard',
    'saveData': 'Save Data',
    'statistics': 'Statistics',
    'usingMaxTestorin': 'Using MaxTestorin',
    'profilePhoto': 'Profile Photo',
    'choosePhotoOption': 'Choose an option to add your photo:',
    'gallery': 'Gallery',
    'camera': 'Camera',
    'permissionNeeded': 'Permission Required',
    'galleryPermission': 'Gallery access permission is required to select a photo.',
    'cameraPermission': 'Camera access permission is required to take a photo.',
    'couldNotSelectImage': 'Could not select the image.',
    'couldNotTakePhoto': 'Could not take the photo.',
    'uploading': 'Uploading...',
    'uploadingImage': 'Uploading image to server...',
    'imageUploadedSuccess': 'Image uploaded successfully!',
    'couldNotUploadImage': 'Could not upload the image.',
    'profileUpdatedSuccess': 'Profile updated successfully!',
    'couldNotSaveProfile': 'Could not save the profile.',
    'logout': 'Logout',
    'logoutConfirmation': 'Are you sure you want to logout?',
    'years': 'years',
    
    // Settings Screen
    'settings': 'Settings',
    'customizeExperience': 'Customize your experience',
    'appearance': 'Appearance',
    'theme': 'Theme',
    'darkModeEnabled': 'Dark mode enabled',
    'lightModeEnabled': 'Light mode enabled',
    'help': 'Help',
    'notifications': 'Notifications',
    'dailyReminders': 'Daily Reminders',
    'receiveNotifications': 'Receive notifications to register usage',
    'goals': 'Goals',
    'dailyGoal': 'Daily Goal',
    'mandatoryDosage': '2 capsules per day (Mandatory Dosage)',
    'weeklyGoal': 'Weekly Goal',
    'weeklyDosage': '14 capsules per week (7 x 2 capsules)',
    'data': 'Data',
    'exportData': 'Export Data',
    'backupRecords': 'Backup your records',
    'clearData': 'Clear Data',
    'deleteAllRecords': 'Delete all records',
    'information': 'Information',
    'aboutMaxTestorin': 'About MaxTestorin',
    'productInformation': 'Product information',
    'privacy': 'Privacy',
    'privacyPolicy': 'Privacy policy',
    'shareApp': 'Share App',
    'inviteFriends': 'Invite friends',
    'language': 'Language',
    'account': 'Account',
    'signOutOfAccount': 'Sign out of your account',
    'personalInformation': 'Personal Information',
    'selectLanguage': 'Select language',
    'portuguese': 'Português',
    'english': 'English',
    'language': 'Language',
    'lightMode': 'Light Mode',
    'darkMode': 'Dark Mode',
    'helpAndSupport': 'Help and Support',
    'shareApplication': 'Share App',
    'developmentFeature': 'Feature in development',
    'reminderConfigured': 'Reminder Configured',
    'dailyNotification': 'You will be notified daily to register MaxTestorin usage.',
    'exportDataFeature': 'This feature allows you to export your data for backup.',
    'inviteFriendsFeature': 'Invite friends to use MaxTestorin Tracker!',
    'correctDosageInfo': '💊 Correct MaxTestorin Dosage',
    'dosageInfo': 'IMPORTANT: The recommended dosage is 2 capsules daily.\n\nMain ingredients:\n• Tribulus Terrestris Extract\n• Peruvian Maca\n• Zinc\n• Vitamin D3\n• Magnesium\n\nHow to use:\n• 2 capsules per day (MANDATORY)\n• Preferably in the morning\n• Can be taken with water\n• Maintain daily regularity',
    'privacyPolicyInfo': 'Your data is stored locally on your device and is not shared with third parties. We take your privacy seriously.',
    'appVersion': 'MaxTestorin Tracker v1.0.0',
    'developedFor': 'Developed to track your progress',
    
    // Logout/Exit
    'exitApp': 'Exit App',
    
    // Clear Data Functionality
    'clearData': 'Clear Data',
    'clearDataWarning': 'WARNING: This action will PERMANENTLY remove all application data:\n\n• Daily usage records\n• Profile information\n• Custom settings\n• Progress history\n• All statistics\n\n⚠️ This action CANNOT be undone!\n\nAre you sure you want to continue?',
    'allDataRemoved': 'All data has been successfully removed.',
    'couldNotRemoveData': 'Could not remove data. Please try again.',
    
    // MaxTestorin Info Popup
    'aboutMaxTestorinTitle': 'About MaxTestorin',
    'aboutMaxTestorinDescription': 'MaxTestorin is a nutraceutical supplement in drops developed to support male well-being. Each drop contains natural ingredients carefully selected for maximum efficacy.',
    'privacyPolicyTitle': 'Privacy Policy',
    'privacyPolicyDescription': 'Your privacy is our priority. This application was developed with a focus on protecting your personal data:\n\n• All data is stored LOCALLY on your device\n• No information is sent to external servers\n• We do not collect personal or usage data\n• We do not share information with third parties\n• You have full control over your data\n• You can export or delete your data at any time\n\nYour MaxTestorin usage records remain private and secure on your device.',
    'close': 'Close',
    
    // Help and Support
    'helpAndSupport': 'Help and Support',
    'needHelp': 'Need Help?',
    'helpDescription': 'Our support team is ready to help you with any questions about MaxTestorin or the app.',
    'emailSupport': 'Email Support',
    'emailSupportDescription': 'Send your questions and get a response within 24 hours',
    'contactSupport': 'Contact Support',
    'copyEmailManually': 'Copy the email manually to get in touch',
    'copyEmail': 'Copy Email',
    'emailCopied': 'Email copied',
    'copyLink': 'Copy Link',
    'frequentQuestions': 'Frequently Asked Questions',
    'faq1': 'How to use MaxTestorin correctly?',
    'faq2': 'What is the recommended daily dosage?',
    'faq3': 'How to track my progress?',
    'faq4': 'How to backup my data?',
    
    // Share App Modal
    'shareAppTitle': 'Share Application',
    'shareAppDescription': '🚀 Help your friends maximize their results!\n\n💪 MaxTestorin Tracker is the perfect app for men who want to:\n\n✅ Track MaxTestorin usage daily\n✅ Monitor progress and consistency\n✅ Maintain treatment discipline\n✅ Achieve better results\n\n🎯 Share with your male friends and help them achieve the same success as you!\n\n📱 App link:\napp.maxtestorin.com',
    
    // Validation Messages
    'enterValidDrops': 'Please enter a valid number of drops.',
    'enterValidCapsules': 'Please enter a valid number of capsules.',
    'enterTime': 'Please enter the usage time.',
    'couldNotSaveRecord': 'Could not save the record.',
    'couldNotUpdateCompletion': 'Could not update the record.',
    'couldNotRemoveData': 'Could not remove the data.',
    'allDataRemoved': 'All data has been removed.',
    
    'drops': 'drops',
    'capsules': 'capsules',
    'capsule': 'capsule',
    'at': 'at',
    'records': 'records',
    'monthlyRecords': 'Monthly Records',
    'monthlyDaysStatus': 'Monthly Days Status',
    
    // Month names
    'january': 'January',
    'february': 'February',
    'march': 'March',
    'april': 'April',
    'may': 'May',
    'june': 'June',
    'july': 'July',
    'august': 'August',
    'september': 'September',
    'october': 'October',
    'november': 'November',
    'december': 'December',
    
    // Purchase notifications
    'purchased': 'purchased',
    
    // Tutorial
    'tutorialTitle': 'Maximize Your Results with the MaxTestorin Tracker!',
    'tutorialSubtitle': 'Watch this quick tutorial to get the most out of your app',
    'skipTutorial': 'Skip Tutorial',
    'watchLater': 'Watch Later',
    'welcomeTutorial': 'Welcome Tutorial',
    'loadingVideo': 'Loading video...',
    
    // Guides Screen
    'guides': 'Guides',
    'learningMaterials': 'Learning materials and resources',
    'categories': 'Categories',
    'allCategories': 'All',
    'nutrition': 'Nutrition',
    'exercise': 'Exercise',
    'lifestyle': 'Lifestyle',
    'science': 'Science',
    'featuredGuides': 'Featured Guides',
    'allGuides': 'All Guides',
    'items': 'items',
    'downloadPDF': 'Download PDF',
    'watchVideo': 'Watch Video',
    'readArticle': 'Read Article',
    'downloadStarted': 'Download Started',
    'downloadStartedMessage': 'Download of "{title}" has started.',
    'cannotOpenFile': 'Cannot open the file.',
    'cannotOpenVideo': 'Cannot open the video.',
    'articleContentNotAvailable': 'Article content not available.',
    'errorOpeningGuide': 'Error opening guide.',
    'noGuidesFound': 'No guides found',
    'tryDifferentCategory': 'Try a different category or search for another term.',
    'aboutGuides': 'About Guides',
    'guidesDescription': 'Our guide library offers scientific information, practical tips, and educational resources to maximize your results with MaxTestorin. All materials are developed by experts.',
    
    // Guide Content
    'maxTestorinCompleteGuide': 'Complete MaxTestorin Guide',
    'completeGuideDescription': 'Complete manual with everything you need to know about MaxTestorin: composition, benefits, usage, and expected results.',
    'nutritionOptimizationGuide': 'Nutrition Optimization Guide',
    'nutritionGuideDescription': 'Nutritional strategies to enhance MaxTestorin effects and improve your overall health.',
    'exerciseRoutineVideo': 'Complementary Exercise Routine',
    'exerciseVideoDescription': 'Video with specific exercises that complement MaxTestorin use for better results.',
    'lifestyleTipsArticle': 'Lifestyle Tips',
    'lifestyleTipsDescription': 'Article with practical lifestyle tips to maximize treatment benefits.',
    'scientificStudyPDF': 'Scientific Studies',
    'scientificStudyDescription': 'Compilation of scientific studies on MaxTestorin ingredients and efficacy.',
    'supplementationGuide': 'Supplementation Guide',
    'supplementationDescription': 'Detailed manual on how to safely combine MaxTestorin with other supplements.',
    
    // Guide Detail Modal
    'downloads': 'Downloads',
    'rating': 'Rating',
    'size': 'Size',
    'duration': 'Duration',
    'rateThisGuide': 'Rate this Guide',
    'thankYou': 'Thank You!',
    'ratingSubmitted': 'Your rating has been submitted successfully.',
    'errorSubmittingRating': 'Error submitting rating.',
    'downloading': 'Downloading...',
    'opening': 'Opening...',
    'viewDetails': 'View Details',
    'at': 'at',
    'of': 'of',
    'completed': 'Completed',
    'pending': 'Pending',
    'toGoal': 'To Goal',
    'totalDrops': 'Total Drops',
    'totalCapsules': 'Total Capsules',
    'swipeToSeeMore': 'Swipe to see more packages',
    'averageDrops': 'Daily Average',
    'averageCapsules': 'Daily Average',
    'remaining': 'Remaining',
    
    // Profile specific translations
    'cityAndState': 'City and State',
    'treatmentGoal': 'Treatment Goal',
  }
};